name: vpho
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pillow=10.2.0=py310h5eee18b_0
  - pip=23.3.1=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - pytorch=2.2.0=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_1
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.0=py310_cu121
  - torchtriton=2.2.0=py310
  - torchvision=0.17.0=py310_cu121
  - typing_extensions=4.9.0=py310h06a4308_1
  - urllib3=2.1.0=py310h06a4308_1
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - addict==2.4.0
      - albumentations==1.4.6
      - annotated-types==0.6.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - blessed==1.21.0
      - blinker==1.7.0
      - bottleneck==1.4.0
      - chumpy==0.70
      - click==8.1.7
      - comm==0.2.1
      - configargparse==1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==0.29.37
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - deepspeed==0.14.2
      - deprecated==1.2.14
      - dex-ycb-toolkit==1.0
      - diffusers==0.27.2
      - easydict==1.13
      - entrypoints==0.4
      - etils==1.7.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - flask==3.0.2
      - fonttools==4.49.0
      - fpsample==0.3.2
      - freetype-py==2.4.0
      - fsspec==2024.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - gpustat==1.1.1
      - hjson==3.1.0
      - huggingface-hub==0.23.1
      - imageio==2.34.0
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipycanvas==0.13.2
      - ipyevents==2.0.2
      - ipython==8.22.2
      - ipywidgets==8.1.2
      - itsdangerous==2.1.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==7.4.9
      - jupyter-core==5.7.1
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - marshmallow==3.21.3
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - mesh-intersection==0.1.0
      - ml-dtypes==0.4.0
      - mujoco==3.2.0
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - nvidia-ml-py==12.575.51
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opendr==0.73
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.2.1
      - parso==0.8.3
      - pexpect==4.9.0
      - platformdirs==4.2.0
      - plotly==5.19.0
      - plyfile==1.0.3
      - portalocker==2.8.2
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pybind11==2.13.1
      - pycocotools==2.0.8
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pyglet==2.0.14
      - pygltflib==1.16.2
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-fcl==0.7.0.6
      - pytz==2024.1
      - pyzmq==26.0.3
      - referencing==0.33.0
      - regex==2024.4.28
      - retrying==1.3.4
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - shapely==2.0.3
      - six==1.16.0
      - smmap==5.0.1
      - smplx==0.1.28
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - timm==0.9.16
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torchgeometry==0.1.2
      - tornado==6.4.1
      - tqdm==4.66.2
      - traitlets==5.14.1
      - transformers==4.41.0
      - transforms3d==0.4.1
      - trimesh==4.1.7
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - usd-core==24.5
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - yacs==0.1.8
      - zipp==3.17.0
prefix: /root/miniconda3/envs/hoi2
